CREATE DATABASE ATV1_SENAI;
USE ATV1_SENAI;

CREATE TABLE Fornecedor (
    Fcodigo INT PRIMARY KEY AUTO_INCREMENT,
    Fnome VARCHAR(100) NOT NULL,
    Status VARCHAR(20) DEFAULT 'Ativo',
    Cidade VARCHAR(100),
    INDEX(Fcodigo)
);

CREATE TABLE Peca (
    Pcodigo INT PRIMARY KEY AUTO_INCREMENT,
    Pnome VARCHAR(100) NOT NULL,
    Cor VARCHAR(50) NOT NULL,
    Peso DECIMAL(10,2) NOT NULL,
    Cidade VARCHAR(100) NOT NULL,
    INDEX(Pcodigo)
);

CREATE TABLE Instituicao (
    Icodigo INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    INDEX(Icodigo)
);

CREATE TABLE Projeto (
    PRcod INT PRIMARY KEY AUTO_INCREMENT,
    PRnome VARCHAR(100) NOT NULL,
    Cidade VARCHAR(100),
    FOREIGN KEY (Icod) REFERENCES Instituicao(Icodigo),
    INDEX(PRcod)
);

CREATE TABLE Fornecimento (
    Fcod INT,
    Pcod INT,
    PRcod INT,
    Quantidade INT NOT NULL,
    PRIMARY KEY (Fcod, Pcod, PRcod),
    FOREIGN KEY (Fcod) REFERENCES Fornecedor(Fcodigo),
    FOREIGN KEY (Pcod) REFERENCES Peca(Pcodigo),
    FOREIGN KEY (PRcod) REFERENCES Projeto(PRcod)
);

CREATE TABLE Cidade (
    Ccod INT PRIMARY KEY AUTO_INCREMENT,
    Cnome VARCHAR(100) NOT NULL,
    UF CHAR(2) NOT NULL
);

ALTER TABLE Fornecedor
    ADD COLUMN Fone VARCHAR(20),
    ADD COLUMN Ccod INT,
    DROP COLUMN CIDADE;

ALTER TABLE Peca
    ADD COLUMN Ccod INT;

ALTER TABLE Projeto
    DROP COLUMN Icod,
    ADD COLUMN Ccod INT;
    
DROP TABLE Instituicao;
